# Generated by Django 5.0.1 on 2024-01-06 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_orders_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="order_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
