# Generated by Django 5.0.1 on 2024-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_rename_value_orders_order_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_value",
            field=models.IntegerField(),
        ),
    ]
